/*
 * No2.java
 *
 * Created on 13 September 2018, 5:48
 */

package DataStream;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  Rizqi
 */
public class No2 extends javax.swing.JFrame {
    
    /** Creates new form No2 */
    Image image= null;
    public No2() {
        initComponents();  
        setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btread = new javax.swing.JButton();
        btshow = new javax.swing.JButton();
        btwrite = new javax.swing.JButton();
        txtdirect = new javax.swing.JTextField();
        lala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btread.setText("Read");
        btread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreadActionPerformed(evt);
            }
        });

        btshow.setText("Show");
        btshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btshowActionPerformed(evt);
            }
        });

        btwrite.setText("Save");
        btwrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwriteActionPerformed(evt);
            }
        });

        txtdirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirectActionPerformed(evt);
            }
        });

        lala.setText("jButton1");
        lala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtdirect, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btread)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btshow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btwrite)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lala)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btread)
                    .addComponent(btshow)
                    .addComponent(btwrite)
                    .addComponent(txtdirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lala)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings("unchecked")
    private void btreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        chooser.setFileFilter(new FileFilter(){
            
            public String getDescription(){
                return "All image support";
            }
            
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()){
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png")
                            || f.getName().toLowerCase().endsWith(".jpeg")
                            || f.getName().toLowerCase().endsWith(".jpg")
                            || f.getName().toLowerCase().endsWith(".gif");
                }
            }
        });
        
        int res = chooser.showOpenDialog(No2.this);
        if(res == JFileChooser.APPROVE_OPTION){
            File file = chooser.getSelectedFile();
            try {
                image = ImageIO.read(file);
            } catch (IOException ex) {
                Logger.getLogger(No2.class.getName()).log(Level.SEVERE, null, ex);
            }
            String name = file.getAbsolutePath();
            txtdirect.setText(name);
        }else {
            JOptionPane.showMessageDialog(this, "Cancelled by User!");
        }
}//GEN-LAST:event_btreadActionPerformed

    private void txtdirectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirectActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtdirectActionPerformed

    private void btwriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwriteActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));

        int r = chooser.showSaveDialog(this);
        if (r==JFileChooser.APPROVE_OPTION){
            File sf = chooser.getSelectedFile();
            try{
                ImageIO.write((RenderedImage) image, "png", sf);

            }catch(IOException ioe){
                JOptionPane.showMessageDialog(null, "Trouble");
            }
            JOptionPane.showMessageDialog(null, "Saved Successfully");
        }else{
            JOptionPane.showMessageDialog(null, "Cancelled by User");
        }
    }//GEN-LAST:event_btwriteActionPerformed

    private void btshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btshowActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
            frame.setLocation(300, 100);
            JLabel label = new JLabel(new ImageIcon(image));
            frame.getContentPane().add(label, BorderLayout.CENTER);
            frame.pack();
            frame.setVisible(true);
    }//GEN-LAST:event_btshowActionPerformed

    private void lalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lalaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new No2().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btread;
    private javax.swing.JButton btshow;
    private javax.swing.JButton btwrite;
    private javax.swing.JButton lala;
    private javax.swing.JTextField txtdirect;
    // End of variables declaration//GEN-END:variables
    
}
